#!/bin/bash

file_log=/tallerlocal/sys/cron/scpDatosEmabesa.log

echo ARRANCANDO SCPDATOSEMABESA >>$file_log
pushd .

echo LOG... >>$file_log
exec >> $file_log
exec 2>> $file_log
date

DIR_COPIA_SEG=/tallerlocal/sys/csAplsProd/postal_discovirtual/emabesa/

DATA_DIR_LOCAL=/tallerlocal/atcanet/cajafuerte/users/ddv/users/emabesa
DATA_DIR_REMOTE=/tallerlocal/atcanet/scp/emabesa

DIR_LOCAL_1=personas
DIR_LOCAL_2=facturas


USER=postal
HOST=10.1.1.5


echo BUSCANDO FICHEROS DE DATOS

  cp -f $DATA_DIR_LOCAL/$DIR_LOCAL_1/*.zip $DIR_COPIA_SEG/$DIR_LOCAL_1
  rm -f $DATA_DIR_LOCAL/$DIR_LOCAL_1/*.info
#  find  $DATA_DIR_LOCAL/$DIR_LOCAL_1 -name *.zip -exec /opt/util/ftpcmd --verbose --src={} --dst=$DATA_DIR_REMOTE/$DIR_REMOTE_1/ --user=$USER --passwd=$PASS --host=$HOST \;
  scp -Bq $DATA_DIR_LOCAL/$DIR_LOCAL_1/*.zip $USER@$HOST:$DATA_DIR_REMOTE/$DIR_LOCAL_1/
  rm -f $DATA_DIR_LOCAL/$DIR_LOCAL_1/*


  cp -f $DATA_DIR_LOCAL/$DIR_LOCAL_2/*.zip $DIR_COPIA_SEG/$DIR_LOCAL_2
  rm -f $DATA_DIR_LOCAL/$DIR_LOCAL_2/*.info
#  find  $DATA_DIR_LOCAL/$DIR_LOCAL_2 -name *.zip -exec /opt/util/ftpcmd --verbose --src={} --dst=$DATA_DIR_REMOTE/$DIR_REMOTE_2/ --user=$USER --passwd=$PASS --host=$HOST \;
  scp -Bq $DATA_DIR_LOCAL/$DIR_LOCAL_2/*.zip $USER@$HOST:$DATA_DIR_REMOTE/$DIR_LOCAL_2/
  rm -f $DATA_DIR_LOCAL/$DIR_LOCAL_2/*

popd
