#!/bin/sh
#
# Startup script for Apache Web Server
#
JAVA_HOME=/opt/jdk

export JAVA_HOME

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
start() {
    echo -n "Starting Sun Java System Application Server: "
    cd /opt/sjsas/bin
    ./asadmin start-domain domain1
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n "Stopping Sun Java System Application Server: "
    cd /opt/sjsas/bin
    ./asadmin stop-domain
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2	
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
