#!/bin/sh
#
# Startup script for Tomcat, the Apache Servlet Engine
#
JAVA_HOME=/opt/jdk
# Necesario para JIRA
JAVA_OPTS=-Dallow.jdk.1.5=true

export JAVA_OPTS JAVA_HOME

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
start() {
    echo -n "Starting TOMCAT "
    cd /opt/tomcat/bin
    su tomcat -c ./startup.sh
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n "Stopping TOMCAT "
    cd /opt/tomcat/bin
    su tomcat -c ./shutdown.sh
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}


# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2	
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
