#!/bin/sh
#
# Startup script for Mysql Data Base
#
JAVA_HOME=/opt/jdk

export JAVA_HOME

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
start() {
    echo -n "Starting MYSQL "
    cd /opt/mysql
    ./bin/mysqld_safe --defaults-file=/opt/mysql/data/my.cnf --user=mysql &
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n "Stopping MYSQL "
    cd /opt/mysql
    ./bin/mysqladmin --defaults-file=/opt/mysql/data/my.cnf shutdown
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2	
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
