#!/bin/sh
#
# Startup script for ALFRESCO
#
JAVA_HOME=/opt/jdk
#JAVA_OPTS=-Dallow.jdk.1.5=true

export JAVA_HOME

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
start() {
    echo -n "Starting ALFRESCO ... "
    cd /opt/alfresco
    su jboss -c ./alfresco.sh start
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n "Stopping ALFRESCO ... "
    cd /opt/alfresco
    su jboss -c ./alfresco.sh stop
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2	
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
