#!/bin/bash
ficheroLog=/mnt/copiaSeguridad/semanallogEscorpio.txt

mount -a -t nfs

rm $ficheroLog

echo "-----------------------------------------------------------" >>$ficheroLog
echo "Copia semanal." `date` >>$ficheroLog
echo "-----------------------------------------------------------" >>$ficheroLog


/atcanet/desarrollo/scripts/bash/copiaSeguridad -i 4 -l $ficheroLog /tallerlocal/atcanet/postal /mnt/copiaSeguridad/postal-auna/semanal cs_postal_auna data/statistic/AUNA data/report/logs/postalEst* data/cnf cnf
