#!/bin/sh
#
# Startup script for OpenLdap, the LDAP Server
#
JAVA_HOME=/opt/jdk

export JAVA_HOME

RETVAL=0

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
start() {
    echo -n $"Starting OPENLDAP "
    cd /opt/openldap/libexec
    ./slapd -f /opt/openldap/etc/openldap/slapd.conf -u ldap -g ldap
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

stop() {
    echo -n $"Stopping OPENLDAP "
    cd /opt/openldap/bin
    kill -INT `cat /opt/openldap/var/run/slapd.pid`
    RETVAL=$?
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
}

# See how we were called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 2	
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
