#!/bin/bash

echo copia tablas GPROY 
/opt/mysql/bin/mysql < flush.portalCorpATCANET.txt


fecha=`date +%Y%m%d_%H%M%S`
tar -zcvf /mnt/copiaSeguridad/mysql/copiaSegGPROY/tablasGPROY$fecha.tgz  /opt/mysql/data/portalCorpATCANET/GPROY_*

