#!/bin/bash

rm $HOME/tempERROR  >/dev/null 2>&1

if [ "$#" == "1" ] ; then

  user=`ps --pid $PPID -o %U --no-headers`
  echo -n .
  
  if [ "$user" == "root" ] ; then
    echo "Este script no cambia palabras de paso de root"
  else
  
    echo -n .
    (sleep 2s; echo $1; sleep 1s; echo $1;) | /usr/bin/smbpasswd $user -s  >$HOME/tempERROR   2>&1
    res=$?
    
    if [ "$res" == "0" ] ; then
    
      echo -n .
      (sleep 2s; echo $1; sleep 1s; echo $1;) | /usr/bin/passwd $user --stdin  >$HOME/tempERROR   2>&1
      res=$?
      
      # Actualizamos las bases de datos NYS por si acaso
      actualizaNYS
      
      if [ "$res" == "0" ] ; then
      
        echo -n .
        /tallerlocal/sys/nfs/atcanet/desarrollo/scripts/bash/changeLDAPInnerProperty "cn=webMail,cn=$user,ou=users,dc=atcanet,dc=com" apassword $1   >$HOME/tempERROR   2>&1
        echo Bien. Palabras de paso cambiadas.
      else
        echo Las palabras de paso locales no han cambiado
        echo porque:
        echo cat $HOME/tempERROR
      fi
    else
      echo Las palabras de paso SAMBA / YP no cambiaron.
      echo porque:
      cat $HOME/tempERROR
    fi
  
    rm $HOME/tempERROR  >/dev/null 2>&1
  fi
else
  echo "uso: cpasswdL <new_password>"
fi